vim.g.mapleader = " "
vim.opt.guicursor = 'n-v-c:block-Cursor/lCursor,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor'
vim.opt.mouse = ""
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.conceallevel = 3 -- nivel de ocultamiento de caracteres en las lineas
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.breakindent = true
vim.opt.smartindent = true
vim.opt.errorbells = false
vim.opt.wrap = true -- wrap para la lineas
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.undodir = os.getenv("~/.cache/nvim/undodir") -- ubicacion de los archivos de deshacer
vim.opt.hlsearch = false                             -- resatado en la busqueda
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 10
vim.opt.sidescrolloff = 10
vim.opt.showmode = false
vim.opt.clipboard = "unnamedplus"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.autowrite = true
vim.opt.list = true
vim.opt.listchars = "tab:»·,nbsp:␣,trail:·,extends:→,precedes:←"
vim.opt.laststatus = 3
vim.opt.updatetime = 100
vim.opt.signcolumn = "yes"
vim.opt.colorcolumn = "120"
vim.opt.shortmess = "filnxtToOFWIcC"
vim.opt.foldenable = false
vim.opt.history = 1000
vim.opt.backup = false      -- desactica el backup de archivos
vim.opt.writebackup = false -- desactica el backup de archivos modificados desde nvim
vim.opt.pumheight = 15      -- Maximo numero de entradas en un popup
vim.opt.wildignore ="*node_modules/**"

vim.g.netrw_browse_split = 0
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 25
