vim.g.mapleader = " "
vim.g.snnipet = "luasnip"
local opt = vim.opt

opt.guicursor = "i:ver30,v:hor30"
opt.mouse = ""
opt.cursorline = true
opt.number = true
opt.relativenumber = true
opt.conceallevel = 3 -- nivel de ocultamiento de caracteres en las lineas
opt.hidden = true    -- oculta los buffers en lugar de cerrarlos
opt.expandtab = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.smartindent = true
opt.errorbells = false
opt.wrap = false -- wrap para la lineas
opt.swapfile = false
opt.undofile = true
opt.undodir = os.getenv "~/.cache/nvim/undodir" -- ubicacion de los archivos de deshacer
opt.hlsearch = false                            -- desactica el resatado en la busqueda
opt.incsearch = true
opt.ignorecase = true
opt.smartcase = true
opt.termguicolors = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.showmode = false
opt.clipboard = "unnamedplus"
opt.splitbelow = true
opt.splitright = true
opt.autowrite = true
opt.list = false
opt.laststatus = 3
opt.cmdheight = 1
opt.updatetime = 400
opt.signcolumn = "yes"
opt.colorcolumn = "120"
opt.equalalways = false
opt.shortmess:append "I"
opt.history = 0
opt.backup = false      -- desactica el backup de archivos
opt.writebackup = false -- desactica el backup de archivos modificados desde nvim
opt.pumheight = 20      -- Maximo numero de entradas en un popup
opt.pumblend = 0        -- Para transparencia de popup
vim.o.langmenu = "es_ES.utf8"
vim.o.helplang = "es"

-- Highlight bracket pairs
vim.opt.showmatch = true
vim.opt.matchtime = 10
